services:
  nifi_optidata:
    build:
      context: ./nifi
      dockerfile: Dockerfile
    container_name: nifi_optidata
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsB0tRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - ./nifi/scripts:/data
    command: ["nifi.sh", "start"]
  spring_optidata:
    container_name: spring_optidata
    build: ./back
    volumes:
      - ./back:/app
      - /home/gradle/.gradle
    ports:
      - "8000:8000"
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GRADLE_OPTS=-Dorg.gradle.unsafe.watch-fs=true
    working_dir: "/app"
    depends_on:
      - mariadb_optidata
  mariadb_optidata:
    image: mariadb:latest
    container_name: mariadb_optidata
    environment:
      MYSQL_DATABASE: optidata
      MYSQL_USER: optidata
      MYSQL_PASSWORD: optidata
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"