services:
  nifi:
    image: nifi_optidata:latest
    container_name: nifi_service
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8443
      - NIFI_WEB_PROXY_HOST=localhost
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USER}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_USER_PASSWORD}
    command: ["nifi.sh", "start"]
    volumes:
      - ./nifi-data:/data  # Volume pour monter ton répertoire local (remplace par ton chemin local)
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: always
volumes:
  mysql_data:
  nifi_data:  # Volume pour persister les données de NiFi
  nifi_conf:  # Volume pour persister les configurations de NiFi

networks:
  app-network:
    driver: bridge

