services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi_service
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8443
      NIFI_PASSWORD: ${NIFI_PASSWORD}
    volumes:
      - ./start-nifi.sh:/start-nifi.sh
    command: >
      /bin/bash -c "/start-nifi.sh"
  mysql:
    image: mysql:latest
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
