version: '3.8'

services:

  nifi:
    image: apache/nifi:latest
    container_name: nifi_service
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8443
    command: >
      /bin/bash -c "
      ./bin/nifi.sh set-single-user-credentials optidata 5f4oZ682Jh09k5w

  mysql:
    image: mysql:latest
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: w6uLYg84XsWn47U
      MYSQL_DATABASE: db_OptiData
      MYSQL_USER: optidata
      MYSQL_PASSWORD: eTpqb9ds2USJuiB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql_data:


networks:
  app-network:

